pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=ci
    actions:
      merge:
        method: squash

  - name: automatic merge of dependabot PRs
    conditions:
      - or:
          - author=dependabot[bot]
          - author=renovate[bot]
      - check-success=ci
      - "#check-success-or-neutral>=1"
    actions:
      merge:
        method: squash

  - name: automatic rebase
    conditions:
      - conflict
    actions:
      rebase: {}
