//! Parity / expansion utilities (`sharecli::util` + library helpers).
//!
//! C00 L1 Phase 1 facade — see `docs/ops/lib-sprawl-plan.md`.
//! Historical file paths under `src/` preserved via `#[path = "../…"]`.

#[path = "../ansi.rs"]
pub mod ansi;
#[path = "../apfs_uuid.rs"]
pub mod apfs_uuid;
#[path = "../api.rs"]
pub mod api;
#[path = "../argparse.rs"]
pub mod argparse;
#[path = "../astar.rs"]
pub mod astar;
#[path = "../backoff.rs"]
pub mod backoff;
#[path = "../base64_util.rs"]
pub mod base64_util;
#[path = "../base64url.rs"]
pub mod base64url;
#[path = "../base85.rs"]
pub mod base85;
#[path = "../binary_search.rs"]
pub mod binary_search;
#[path = "../binary_search_ex.rs"]
pub mod binary_search_ex;
#[path = "../bip39_mnemonic.rs"]
pub mod bip39_mnemonic;
#[path = "../bip39_wordlist.rs"]
pub mod bip39_wordlist;
#[path = "../bloom.rs"]
pub mod bloom;
#[path = "../bloom_filter.rs"]
pub mod bloom_filter;
#[path = "../bucks.rs"]
pub mod bucks;
#[path = "../cache.rs"]
pub mod cache;
#[path = "../catalan_number.rs"]
pub mod catalan_number;
#[path = "../cdp_meraki_discovery.rs"]
pub mod cdp_meraki_discovery;
#[path = "../chacha20.rs"]
pub mod chacha20;
#[path = "../color.rs"]
pub mod color;
#[path = "../crc64.rs"]
pub mod crc64;
#[path = "../credit_card.rs"]
pub mod credit_card;
#[path = "../cron_parser.rs"]
pub mod cron_parser;
#[path = "../csv_util.rs"]
pub mod csv_util;
#[path = "../csv_writer.rs"]
pub mod csv_writer;
#[path = "../cyclic_check.rs"]
pub mod cyclic_check;
#[path = "../deque.rs"]
pub mod deque;
#[path = "../dhcpv6_msg.rs"]
pub mod dhcpv6_msg;
#[path = "../disjoint_set.rs"]
pub mod disjoint_set;
#[path = "../distance.rs"]
pub mod distance;
#[path = "../dnssec_chain.rs"]
pub mod dnssec_chain;
#[path = "../feature_flags.rs"]
pub mod feature_flags;
#[path = "../flatbuffers_lite.rs"]
pub mod flatbuffers_lite;
#[path = "../glob_pattern.rs"]
pub mod glob_pattern;
#[path = "../graph.rs"]
pub mod graph;
#[path = "../hash_util.rs"]
pub mod hash_util;
#[path = "../hkdf.rs"]
pub mod hkdf;
#[path = "../html_escape.rs"]
pub mod html_escape;
#[path = "../ini_parser.rs"]
pub mod ini_parser;
#[path = "../ipaddr_validation.rs"]
pub mod ipaddr_validation;
#[path = "../ipv4_util.rs"]
pub mod ipv4_util;
#[path = "../itoa.rs"]
pub mod itoa;
#[path = "../json_pointer.rs"]
pub mod json_pointer;
#[path = "../jsonpath_lite.rs"]
pub mod jsonpath_lite;
#[path = "../jsonschema_subset.rs"]
pub mod jsonschema_subset;
#[path = "../keccak.rs"]
pub mod keccak;
#[path = "../kmp_search.rs"]
pub mod kmp_search;
#[path = "../lazy.rs"]
pub mod lazy;
#[path = "../levenshtein.rs"]
pub mod levenshtein;
#[path = "../lru.rs"]
pub mod lru;
#[path = "../lru_cache_ext.rs"]
pub mod lru_cache_ext;
#[path = "../macho_parse.rs"]
pub mod macho_parse;
#[path = "../mapi_props.rs"]
pub mod mapi_props;
#[path = "../mapi_props_parity.rs"]
pub mod mapi_props_parity;
#[path = "../markdown_inline.rs"]
pub mod markdown_inline;
#[path = "../matrix.rs"]
pub mod matrix;
#[path = "../matrix_ops.rs"]
pub mod matrix_ops;
#[path = "../md_table.rs"]
pub mod md_table;
#[path = "../mime_qp.rs"]
pub mod mime_qp;
#[path = "../msgpack.rs"]
pub mod msgpack;
#[path = "../natural_sort.rs"]
pub mod natural_sort;
#[path = "../ntp_timestamp.rs"]
pub mod ntp_timestamp;
#[path = "../object_pool.rs"]
pub mod object_pool;
#[path = "../pem_decode.rs"]
pub mod pem_decode;
#[path = "../perm.rs"]
pub mod perm;
#[path = "../pin.rs"]
pub mod pin;
#[path = "../priority_queue.rs"]
pub mod priority_queue;
#[path = "../queue.rs"]
pub mod queue;
#[path = "../queue2.rs"]
pub mod queue2;
#[path = "../radix_trie.rs"]
pub mod radix_trie;
#[path = "../rate_limiter.rs"]
pub mod rate_limiter;
#[path = "../rational.rs"]
pub mod rational;
#[path = "../retry.rs"]
pub mod retry;
#[path = "../ring_buffer.rs"]
pub mod ring_buffer;
#[path = "../segment_tree_basic.rs"]
pub mod segment_tree_basic;
#[path = "../sha3_keccak.rs"]
pub mod sha3_keccak;
#[path = "../skiplist.rs"]
pub mod skiplist;
#[path = "../slice_ext.rs"]
pub mod slice_ext;
#[path = "../sliding_window.rs"]
pub mod sliding_window;
#[path = "../sorted_vec.rs"]
pub mod sorted_vec;
#[path = "../sortedset.rs"]
pub mod sortedset;
#[path = "../sqrt_integer.rs"]
pub mod sqrt_integer;
#[path = "../stack.rs"]
pub mod stack;
#[path = "../stats.rs"]
pub mod stats;
#[path = "../stopwatch.rs"]
pub mod stopwatch;
#[path = "../stream.rs"]
pub mod stream;
#[path = "../tar_util.rs"]
pub mod tar_util;
#[path = "../template.rs"]
pub mod template;
#[path = "../text_slab.rs"]
pub mod text_slab;
#[path = "../toml_lite.rs"]
pub mod toml_lite;
#[path = "../topological_sort.rs"]
pub mod topological_sort;
#[path = "../trie_compressed.rs"]
pub mod trie_compressed;
#[path = "../trim.rs"]
pub mod trim;
#[path = "../typed_id.rs"]
pub mod typed_id;
#[path = "../url_safe_base64.rs"]
pub mod url_safe_base64;
#[path = "../utf8v.rs"]
pub mod utf8v;
#[path = "../uuid.rs"]
pub mod uuid;
#[path = "../uuid_v7.rs"]
pub mod uuid_v7;
#[path = "../vlq.rs"]
pub mod vlq;
#[path = "../word_count.rs"]
pub mod word_count;
#[path = "../xml_escape.rs"]
pub mod xml_escape;
#[path = "../xxhash3.rs"]
pub mod xxhash3;
#[path = "../xxtea.rs"]
pub mod xxtea;
#[path = "../zip_crc32.rs"]
pub mod zip_crc32;
