//! Parity / expansion utilities (`sharecli::util` + library helpers).
//!
//! C00 L1 Phase 1 facade — see `docs/ops/lib-sprawl-plan.md`.
//! Historical file paths under `src/` preserved via `#[path = "../…"]`.

#[path = "../ansi.rs"]
pub mod ansi;
#[path = "../apfs_uuid.rs"]
pub mod apfs_uuid;
#[path = "../api.rs"]
pub mod api;
#[path = "../argparse.rs"]
pub mod argparse;
#[path = "../asn1_ber.rs"]
pub mod asn1_ber;
#[path = "../asn1_ber_parity.rs"]
pub mod asn1_ber_parity;
#[path = "../astar.rs"]
pub mod astar;
#[path = "../backoff.rs"]
pub mod backoff;
#[path = "../base64_util.rs"]
pub mod base64_util;
#[path = "../base64url.rs"]
pub mod base64url;
#[path = "../base85.rs"]
pub mod base85;
#[path = "../base_n_radix.rs"]
pub mod base_n_radix;
#[path = "../bellman_ford.rs"]
pub mod bellman_ford;
#[path = "../binary_search.rs"]
pub mod binary_search;
#[path = "../binary_search_ex.rs"]
pub mod binary_search_ex;
#[path = "../bip39_mnemonic.rs"]
pub mod bip39_mnemonic;
#[path = "../bip39_wordlist.rs"]
pub mod bip39_wordlist;
#[path = "../bitcoin_bech32.rs"]
pub mod bitcoin_bech32;
#[path = "../blake2.rs"]
pub mod blake2;
#[path = "../bloom.rs"]
pub mod bloom;
#[path = "../bloom_filter.rs"]
pub mod bloom_filter;
#[path = "../bmp_image.rs"]
pub mod bmp_image;
#[path = "../bucks.rs"]
pub mod bucks;
#[path = "../cache.rs"]
pub mod cache;
#[path = "../catalan_number.rs"]
pub mod catalan_number;
#[path = "../cdp_meraki_discovery.rs"]
pub mod cdp_meraki_discovery;
#[path = "../chacha20.rs"]
pub mod chacha20;
#[path = "../coap_option_parse.rs"]
pub mod coap_option_parse;
#[path = "../color.rs"]
pub mod color;
#[path = "../crc64.rs"]
pub mod crc64;
#[path = "../credit_card.rs"]
pub mod credit_card;
#[path = "../cron_parser.rs"]
pub mod cron_parser;
#[path = "../csv_util.rs"]
pub mod csv_util;
#[path = "../csv_writer.rs"]
pub mod csv_writer;
#[path = "../cue_sheet.rs"]
pub mod cue_sheet;
#[path = "../cyclic_check.rs"]
pub mod cyclic_check;
#[path = "../deque.rs"]
pub mod deque;
#[path = "../dhcp_options.rs"]
pub mod dhcp_options;
#[path = "../dhcpv6_msg.rs"]
pub mod dhcpv6_msg;
#[path = "../disjoint_set.rs"]
pub mod disjoint_set;
#[path = "../distance.rs"]
pub mod distance;
#[path = "../dns_query_parser.rs"]
pub mod dns_query_parser;
#[path = "../dns_zone.rs"]
pub mod dns_zone;
#[path = "../dnssec_chain.rs"]
pub mod dnssec_chain;
#[path = "../erf.rs"]
pub mod erf;
#[path = "../feature_flags.rs"]
pub mod feature_flags;
#[path = "../flac_metadata_block.rs"]
pub mod flac_metadata_block;
#[path = "../flatbuffers_lite.rs"]
pub mod flatbuffers_lite;
#[path = "../glob_pattern.rs"]
pub mod glob_pattern;
#[path = "../graph.rs"]
pub mod graph;
#[path = "../hash_util.rs"]
pub mod hash_util;
#[path = "../hkdf.rs"]
pub mod hkdf;
#[path = "../html_escape.rs"]
pub mod html_escape;
#[path = "../imap_response.rs"]
pub mod imap_response;
#[path = "../ini_parser.rs"]
pub mod ini_parser;
#[path = "../ipaddr_validation.rs"]
pub mod ipaddr_validation;
#[path = "../ipsec_esp_parse.rs"]
pub mod ipsec_esp_parse;
#[path = "../ipv4_util.rs"]
pub mod ipv4_util;
#[path = "../itoa.rs"]
pub mod itoa;
#[path = "../json5.rs"]
pub mod json5;
#[path = "../json_pointer.rs"]
pub mod json_pointer;
#[path = "../jsonpath_lite.rs"]
pub mod jsonpath_lite;
#[path = "../jsonschema_subset.rs"]
pub mod jsonschema_subset;
#[path = "../keccak.rs"]
pub mod keccak;
#[path = "../kmp_search.rs"]
pub mod kmp_search;
#[path = "../lazy.rs"]
pub mod lazy;
#[path = "../ldap_filter.rs"]
pub mod ldap_filter;
#[path = "../levenshtein.rs"]
pub mod levenshtein;
#[path = "../lru.rs"]
pub mod lru;
#[path = "../lru_cache_ext.rs"]
pub mod lru_cache_ext;
#[path = "../lz4_block.rs"]
pub mod lz4_block;
#[path = "../m3u8_playlist.rs"]
pub mod m3u8_playlist;
#[path = "../macho_parse.rs"]
pub mod macho_parse;
#[path = "../mapi_props.rs"]
pub mod mapi_props;
#[path = "../mapi_props_parity.rs"]
pub mod mapi_props_parity;
#[path = "../markdown_inline.rs"]
pub mod markdown_inline;
#[path = "../matrix.rs"]
pub mod matrix;
#[path = "../matrix_ops.rs"]
pub mod matrix_ops;
#[path = "../md_table.rs"]
pub mod md_table;
#[path = "../mime_qp.rs"]
pub mod mime_qp;
#[path = "../money.rs"]
pub mod money;
#[path = "../mp4_box.rs"]
pub mod mp4_box;
#[path = "../msgpack.rs"]
pub mod msgpack;
#[path = "../natural_sort.rs"]
pub mod natural_sort;
#[path = "../ntp_timestamp.rs"]
pub mod ntp_timestamp;
#[path = "../oauth1_signature.rs"]
pub mod oauth1_signature;
#[path = "../object_pool.rs"]
pub mod object_pool;
#[path = "../pem_decode.rs"]
pub mod pem_decode;
#[path = "../perm.rs"]
pub mod perm;
#[path = "../pin.rs"]
pub mod pin;
#[path = "../pres_header_parity.rs"]
pub mod pres_header_parity;
#[path = "../pres_header_parse.rs"]
pub mod pres_header_parse;
#[path = "../priority_queue.rs"]
pub mod priority_queue;
#[path = "../qoi_image.rs"]
pub mod qoi_image;
#[path = "../queue.rs"]
pub mod queue;
#[path = "../queue2.rs"]
pub mod queue2;
#[path = "../radix_trie.rs"]
pub mod radix_trie;
#[path = "../rate_limiter.rs"]
pub mod rate_limiter;
#[path = "../rational.rs"]
pub mod rational;
#[path = "../rdp_neg.rs"]
pub mod rdp_neg;
#[path = "../retry.rs"]
pub mod retry;
#[path = "../ring_buffer.rs"]
pub mod ring_buffer;
#[path = "../roman_numeral.rs"]
pub mod roman_numeral;
#[path = "../s_expression.rs"]
pub mod s_expression;
#[path = "../segment_tree_basic.rs"]
pub mod segment_tree_basic;
#[path = "../sha3_keccak.rs"]
pub mod sha3_keccak;
#[path = "../skiplist.rs"]
pub mod skiplist;
#[path = "../slice_ext.rs"]
pub mod slice_ext;
#[path = "../sliding_window.rs"]
pub mod sliding_window;
#[path = "../smtp_envelope.rs"]
pub mod smtp_envelope;
#[path = "../snmpv3_msg.rs"]
pub mod snmpv3_msg;
#[path = "../sorted_vec.rs"]
pub mod sorted_vec;
#[path = "../sortedset.rs"]
pub mod sortedset;
#[path = "../sqrt_integer.rs"]
pub mod sqrt_integer;
#[path = "../ssh_known_hosts.rs"]
pub mod ssh_known_hosts;
#[path = "../ssh_packet.rs"]
pub mod ssh_packet;
#[path = "../stack.rs"]
pub mod stack;
#[path = "../stats.rs"]
pub mod stats;
#[path = "../stopwatch.rs"]
pub mod stopwatch;
#[path = "../stream.rs"]
pub mod stream;
#[path = "../tar_header.rs"]
pub mod tar_header;
#[path = "../tar_util.rs"]
pub mod tar_util;
#[path = "../template.rs"]
pub mod template;
#[path = "../text_slab.rs"]
pub mod text_slab;
#[path = "../toml_lite.rs"]
pub mod toml_lite;
#[path = "../topological_sort.rs"]
pub mod topological_sort;
#[path = "../trie_compressed.rs"]
pub mod trie_compressed;
#[path = "../trim.rs"]
pub mod trim;
#[path = "../typed_id.rs"]
pub mod typed_id;
#[path = "../url_safe_base64.rs"]
pub mod url_safe_base64;
#[path = "../utf8v.rs"]
pub mod utf8v;
#[path = "../uuid.rs"]
pub mod uuid;
#[path = "../uuid_v7.rs"]
pub mod uuid_v7;
#[path = "../vector_3d.rs"]
pub mod vector_3d;
#[path = "../vlq.rs"]
pub mod vlq;
#[path = "../wasm_opcode.rs"]
pub mod wasm_opcode;
#[path = "../webmanifest.rs"]
pub mod webmanifest;
#[path = "../webvtt_cue.rs"]
pub mod webvtt_cue;
#[path = "../word_count.rs"]
pub mod word_count;
#[path = "../x12_edi_segment.rs"]
pub mod x12_edi_segment;
#[path = "../x509_chain.rs"]
pub mod x509_chain;
#[path = "../xml_escape.rs"]
pub mod xml_escape;
#[path = "../xxhash3.rs"]
pub mod xxhash3;
#[path = "../xxtea.rs"]
pub mod xxtea;
#[path = "../zip_crc32.rs"]
pub mod zip_crc32;
