//! C08 L76 — Harbor soak nightly gate (T-980)
//! FR: FR-008
//! Scope: soak config existence, duration threshold assertions, and
//!        report format validation against the real soak harness output.

use std::fs;
use std::path::Path;

/// Default soak config that the CI workflow drops if none exists yet.
const DEFAULT_SOAK_YAML: &str = r#"# soak.yaml - minimal default config generated by CI
# T-980: Harbor soak nightly gate
duration_seconds: 600
report_file: soak-report.json
thresholds:
  max_error_rate: 0.05
  min_uptime_pct: 95.0
  max_p99_latency_ms: 2000
scenarios:
  - name: healthz
    command: ["sharecli", "health", "--json"]
    timeout_secs: 10
"#;

/// Minimum acceptable soak duration in seconds.
const MIN_SOAK_DURATION_SEC: u64 = 60;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn soak_harness_exists() {
    let soak_config = Path::new("soak.yaml");

    if soak_config.exists() {
        let content = fs::read_to_string(soak_config).expect("soak.yaml is readable");
        assert!(!content.trim().is_empty(), "soak.yaml must not be empty");
    } else {
        // Create a default config so downstream CI steps have a valid file.
        fs::write(soak_config, DEFAULT_SOAK_YAML).expect("failed to create default soak.yaml");
        let content =
            fs::read_to_string(soak_config).expect("soak.yaml is readable after creation");
        assert!(
            content.contains("duration_seconds"),
            "default soak.yaml must contain duration_seconds"
        );
    }
}

#[test]
fn soak_duration_reasonable() {
    let soak_config = Path::new("soak.yaml");

    if soak_config.exists() {
        let content = fs::read_to_string(soak_config).expect("soak.yaml is readable");
        let duration = content
            .lines()
            .find(|l| l.trim_start().starts_with("duration_seconds:"))
            .map(|l| l.split(':').nth(1).unwrap_or("0").trim().parse::<u64>().unwrap_or(0))
            .unwrap_or(0);

        assert!(
            duration >= MIN_SOAK_DURATION_SEC,
            "soak duration_seconds ({duration}) must be >= {MIN_SOAK_DURATION_SEC}"
        );
    } else {
        let duration = DEFAULT_SOAK_YAML
            .lines()
            .find(|l| l.trim_start().starts_with("duration_seconds:"))
            .map(|l| l.split(':').nth(1).unwrap_or("0").trim().parse::<u64>().unwrap_or(0))
            .unwrap_or(0);

        assert!(
            duration >= MIN_SOAK_DURATION_SEC,
            "default soak duration_seconds ({duration}) must be >= {MIN_SOAK_DURATION_SEC}"
        );
    }
}

#[test]
fn soak_config_has_scenarios() {
    let soak_config = Path::new("soak.yaml");
    if soak_config.exists() {
        let content = fs::read_to_string(soak_config).expect("soak.yaml is readable");
        assert!(content.contains("scenarios:"), "soak.yaml must define scenarios");
        assert!(content.contains("healthz"), "soak.yaml must include a healthz scenario");
    }
}

#[test]
fn soak_config_has_thresholds() {
    let soak_config = Path::new("soak.yaml");
    if soak_config.exists() {
        let content = fs::read_to_string(soak_config).expect("soak.yaml is readable");
        assert!(content.contains("thresholds:"), "soak.yaml must define thresholds");
        assert!(
            content.contains("max_error_rate"),
            "soak.yaml thresholds must include max_error_rate"
        );
        assert!(
            content.contains("min_uptime_pct"),
            "soak.yaml thresholds must include min_uptime_pct"
        );
        assert!(
            content.contains("max_p99_latency_ms"),
            "soak.yaml thresholds must include max_p99_latency_ms"
        );
    }
}

#[test]
fn soak_report_format_if_exists() {
    // If a soak-report.json exists (from a prior run or CI), validate
    // that it has the expected top-level keys produced by the real
    // soak harness (commands/soak.rs).
    let report = Path::new("soak-report.json");
    if report.exists() {
        let content = fs::read_to_string(report).expect("soak-report.json is readable");
        // Validate presence of all required fields from SoakReport
        assert!(content.contains("\"version\""), "report must have version");
        assert!(content.contains("\"sha\""), "report must have sha");
        assert!(content.contains("\"duration_sec\""), "report must have duration_sec");
        assert!(content.contains("\"interval_sec\""), "report must have interval_sec");
        assert!(content.contains("\"started_at\""), "report must have started_at");
        assert!(content.contains("\"finished_at\""), "report must have finished_at");
        assert!(content.contains("\"total_requests\""), "report must have total_requests");
        assert!(content.contains("\"error_rate\""), "report must have error_rate");
        assert!(content.contains("\"uptime_pct\""), "report must have uptime_pct");
        assert!(content.contains("\"p99_latency_ms\""), "report must have p99_latency_ms");
        assert!(content.contains("\"p50_latency_ms\""), "report must have p50_latency_ms");
        assert!(content.contains("\"max_memory_bytes\""), "report must have max_memory_bytes");
        assert!(content.contains("\"scenario_results\""), "report must have scenario_results");
    }
}

#[test]
fn soak_subcommand_exists_in_binary_help() {
    // Verify the soak subcommand is registered in the CLI help.
    let output = std::process::Command::new(env!("CARGO_BIN_EXE_sharecli"))
        .arg("--help")
        .output()
        .expect("failed to run sharecli --help");
    let help = String::from_utf8_lossy(&output.stdout);
    assert!(help.contains("soak"), "sharecli --help must mention 'soak' subcommand");
    assert!(
        help.contains("Harbor soak") || help.contains("stability"),
        "sharecli --help must describe soak as stability evaluation"
    );
}
