//! C08 L76 — Harbor soak nightly gate (T-980)
//! FR: FR-008
//! Scope: soak config existence and duration threshold assertions.

use std::fs;
use std::path::Path;

/// Default soak config that the CI workflow drops if none exists yet.
const DEFAULT_SOAK_YAML: &str = r#"# soak.yaml — minimal default config generated by CI
# T-980: Harbor soak nightly gate
duration_seconds: 600
report_file: soak-report.json
thresholds:
  max_error_rate: 0.05
  min_uptime_pct: 95.0
  max_p99_latency_ms: 2000
"#;

/// Minimum acceptable soak duration in seconds.
const MIN_SOAK_DURATION_SEC: u64 = 60;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn soak_harness_exists() {
    let soak_config = Path::new("soak.yaml");

    if soak_config.exists() {
        let content =
            fs::read_to_string(soak_config).expect("soak.yaml is readable");
        assert!(
            !content.trim().is_empty(),
            "soak.yaml must not be empty"
        );
    } else {
        // Create a default config so downstream CI steps have a valid file.
        fs::write(soak_config, DEFAULT_SOAK_YAML)
            .expect("failed to create default soak.yaml");
        let content =
            fs::read_to_string(soak_config).expect("soak.yaml is readable after creation");
        assert!(
            content.contains("duration_seconds"),
            "default soak.yaml must contain duration_seconds"
        );
    }
}

#[test]
fn soak_duration_reasonable() {
    let soak_config = Path::new("soak.yaml");

    if soak_config.exists() {
        let content =
            fs::read_to_string(soak_config).expect("soak.yaml is readable");
        // Parse the duration_seconds value manually (no serde_yaml dep in
        // integration tests).
        let duration = content
            .lines()
            .find(|l| l.trim_start().starts_with("duration_seconds:"))
            .map(|l| {
                l.split(':')
                    .nth(1)
                    .unwrap_or("0")
                    .trim()
                    .parse::<u64>()
                    .unwrap_or(0)
            })
            .unwrap_or(0);

        assert!(
            duration >= MIN_SOAK_DURATION_SEC,
            "soak duration_seconds ({duration}) must be >= {MIN_SOAK_DURATION_SEC}"
        );
    } else {
        // No soak.yaml present — verify that the default we would create
        // has a reasonable duration.
        let duration = DEFAULT_SOAK_YAML
            .lines()
            .find(|l| l.trim_start().starts_with("duration_seconds:"))
            .map(|l| {
                l.split(':')
                    .nth(1)
                    .unwrap_or("0")
                    .trim()
                    .parse::<u64>()
                    .unwrap_or(0)
            })
            .unwrap_or(0);

        assert!(
            duration >= MIN_SOAK_DURATION_SEC,
            "default soak duration_seconds ({duration}) must be >= {MIN_SOAK_DURATION_SEC}"
        );
    }
}
